name: Publish to crates.io
on:
  workflow_dispatch: # only on manual triggering

jobs:
  publish:
    name: Publish
    runs-on: ubuntu-latest
    environment: crates.io
    steps:
      - name: Checkout sources
        uses: actions/checkout@v4
      - run: cargo publish --token ${CRATES_TOKEN}
        env:
          CRATES_TOKEN: ${{ secrets.CRATES_TOKEN }}
