name: Rust

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

env:
  CARGO_TERM_COLOR: always

jobs:
  test-std:
    name: "Test (std)"
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v7
      - uses: dtolnay/rust-toolchain@stable
      - name: Rust dependency cache
        uses: Swatinem/rust-cache@v2
      - name: Compile and run tests
        run: cargo test --no-fail-fast

  test-no-std:
    name: "Test (no-std)"
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v7
      - uses: dtolnay/rust-toolchain@stable
      - name: Rust dependency cache
        uses: Swatinem/rust-cache@v2
      - name: Compile and run tests
        run: cargo test -p rapidhash --no-fail-fast --lib --tests --no-default-features

  test-unsafe:
    name: "Test (unsafe)"
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v7
      - uses: dtolnay/rust-toolchain@stable
      - name: Rust dependency cache
        uses: Swatinem/rust-cache@v2
      - name: Compile and run tests
        run: cargo test -p rapidhash --no-fail-fast --lib --tests --features=unsafe

  test-nightly-all-features:
    name: "Test (nightly, all features)"
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v7
      - uses: dtolnay/rust-toolchain@stable
        with:
          toolchain: nightly
      - name: Rust dependency cache
        uses: Swatinem/rust-cache@v2
      - name: Compile and run tests
        run: cargo +nightly test -p rapidhash --no-fail-fast --lib --tests --all-features

  test-nightly-no-std:
    name: "Test (nightly, no-std)"
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v7
      - uses: dtolnay/rust-toolchain@stable
        with:
          toolchain: nightly
      - name: Rust dependency cache
        uses: Swatinem/rust-cache@v2
      - name: Compile and run tests (no_std)
        run: cargo +nightly test -p rapidhash --no-fail-fast --lib --tests --no-default-features

  test-32-bit:
    name: "Test (32-bit)"
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v7
      - uses: dtolnay/rust-toolchain@stable
        with:
          target: i686-unknown-linux-gnu
      - name: Install 32-bit C/C++ toolchain
        run: |
          sudo apt-get update
          sudo apt-get install -y gcc-multilib g++-multilib
      - name: Rust dependency cache
        uses: Swatinem/rust-cache@v2
      - name: Compile and run tests (no_std)
        run: cargo test --target i686-unknown-linux-gnu -p rapidhash --no-fail-fast --lib --tests

  test-msrv:
    name: "Test (MSRV)"
    runs-on: ubuntu-latest
    env:
      RUST_VERSION: 1.71.0
    steps:
      - uses: actions/checkout@v7
      - name: Rust dependency cache
        uses: Swatinem/rust-cache@v2
      - name: Install Rust (rustup, ${{ env.RUST_VERSION }})
        shell: bash
        run: rustup update ${{ env.RUST_VERSION }} --no-self-update && rustup default ${{ env.RUST_VERSION }} && cargo -V && rustc -V
      - name: Compile and run tests (no-std)
        working-directory: rapidhash-msrv
        run: cargo test --no-fail-fast --no-default-features
      - name: Compile and run tests (all features)
        working-directory: rapidhash-msrv
        run: cargo test --no-fail-fast --all-features

  test-c:
    name: "Test (C implementations)"
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v7
      - uses: dtolnay/rust-toolchain@stable
      - name: Rust dependency cache
        uses: Swatinem/rust-cache@v2
      - name: Compile and run tests
        run: cargo test -p rapidhash-c --no-fail-fast

  test-docs:
    name: "Test (docs)"
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v7
      - uses: dtolnay/rust-toolchain@stable
      - name: Rust dependency cache
        uses: Swatinem/rust-cache@v2
      - name: Compile and run tests
        run: RUSTDOCFLAGS="--cfg docsrs" cargo +nightly test -p rapidhash --all-features --doc --no-fail-fast

  test-wasm:
    # Check compiling for the webassembly target with default features.
    name: "Build (wasm)"
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v7
      - uses: dtolnay/rust-toolchain@stable
      - name: Rust dependency cache
        uses: Swatinem/rust-cache@v2
      - name: Install wasm targets
        run: rustup target add wasm32-unknown-unknown wasm32-wasip1
      - name: Compile and run tests
        run: cargo build -p rapidhash --target wasm32-unknown-unknown
      - name: Run wasm behaviour tests (with and without getrandom)
        run: cargo test -p rapidhash-bench-wasm --test wasm_behaviour --no-fail-fast

  test-no-atomics:
    # Check that a no-atomics target compiles, but it sadly can't run tests
    name: "Build (no atomics)"
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v7
      - uses: dtolnay/rust-toolchain@stable
      - name: Rust dependency cache
        uses: Swatinem/rust-cache@v2
      - name: Install no-atomics target
        run: rustup target add thumbv6m-none-eabi
      - name: Compile and run tests
        run: cargo build -p rapidhash --no-default-features --lib --target thumbv6m-none-eabi
      - name: Compile with a getrandom custom backend
        run: RUSTFLAGS='--cfg getrandom_backend="custom"' cargo build -p rapidhash --no-default-features --features getrandom_04 --lib --target thumbv6m-none-eabi
